version: "3.8"
services:

  frontend:
    image: metcalfc/timestamper
    ports:
      - "5000:5000"
    secrets:
      - db_password
    depends_on:
      - backend

  backend:
    image: redis:alpine
    command: ["sh", "-c", "redis-server --requirepass \"$$(cat /run/secrets/db_password)\""]
    secrets:
      - db_password

secrets:
  db_password:
    file: secret.txt
